# Generated by Django 5.1.4 on 2025-06-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pages_required', models.PositiveIntegerField(default=0)),
                ('estimated_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('old_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('old_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('old_date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user_type', models.JSONField(default=list)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Account Holder's Name")),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('account_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=25)),
                ('bank_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Pigme', 'Pigme'), ('Mutual Fund', 'Mutual Fund'), ('Digital Gold', 'Digital Gold'), ('Trading', 'Trading')], max_length=25, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Business', 'Business')], max_length=10, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'indexes': [models.Index(fields=['account_number'], name='api_account_account_32cec2_idx'), models.Index(fields=['account_holder_name'], name='api_account_account_b5a926_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('core_category', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=20, null=True)),
                ('category_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Shop', 'Shop')], max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'ordering': ['core_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=255)),
                ('requirement_type', models.CharField(choices=[('Document', 'Document'), ('Info', 'Information'), ('Verification', 'Verification')], default='Document', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTempEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('new_adhar', 'New Adhar'), ('mobile_change', 'Mobile Number Change'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name Change'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('update_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('ucl', 'UCL')], default='offline', max_length=15)),
                ('entry_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='update', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('new_adhar', 'New Adhar'), ('mobile_change', 'Mobile Number Change'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name Change'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('is_miscellaneous', models.BooleanField(default=False, help_text='True if this is a non-standard or walk-in transaction.')),
                ('update_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('ucl', 'UCL')], default='offline', max_length=15)),
                ('entry_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='update', max_length=10)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=510, null=True)),
                ('area', models.CharField(blank=True, max_length=510, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('post_office', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_dist', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(blank=True, choices=[('Aadhaar', 'Aadhaar'), ('Pancard', 'Pancard'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Ration Card', 'Ration Card'), ('BOCW', 'BOCW'), ('Aapaar ID', 'Aapaar ID'), ('ABHA ID', 'ABHA ID'), ('Other', 'Other')], max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('other_doc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='api.user')),
            ],
        ),
    ]
