# Generated by Django 5.1.4 on 2025-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
