# Generated by Django 5.1.4 on 2025-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Shop', 'Shop')], default='Home', max_length=10),
        ),
    ]
