# Generated by Django 5.1.4 on 2025-02-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Shop', 'Shop')], max_length=10, null=True),
        ),
    ]
