# Generated by Django 5.1.4 on 2025-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='passport_required',
            field=models.BooleanField(default=False, help_text='Is passport required?'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of passport photos required'),
        ),
    ]
