# Generated by Django 5.1.4 on 2025-06-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicegroup'),
        ),
    ]
