# Generated by Django 5.1.4 on 2025-07-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_service_passport_required_service_photo_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdocument',
            name='service',
        ),
        migrations.CreateModel(
            name='ServiceSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('supporting_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supportingdocument')),
            ],
            options={
                'unique_together': {('service', 'supporting_document')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='supporting_documents',
            field=models.ManyToManyField(related_name='services', through='api.ServiceSupportingDocument', to='api.supportingdocument'),
        ),
    ]
