# Generated by Django 5.1.4 on 2025-06-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_service_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='department',
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.servicegroup'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicegroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
