# Generated by Django 5.1.4 on 2025-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_supportingdocument_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_name',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='other_doc_name',
        ),
        migrations.AddField(
            model_name='userid',
            name='id_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userid',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
