# Generated by Django 5.1.4 on 2025-06-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_servicegroup_department_servicegroup_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_group',
        ),
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.servicedepartment')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicedepartment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceGroup',
        ),
    ]
