# Generated by Django 5.1.4 on 2025-06-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_service_service_group_servicedepartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedepartment',
            name='child',
        ),
        migrations.AddField(
            model_name='servicedepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.servicedepartment'),
        ),
    ]
