# Generated by Django 5.1.4 on 2025-10-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_old_date_of_birth_remove_user_old_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetempentry',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicetempentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='service',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(choices=[('personal', 'Personal'), ('Shop', 'Shop')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(choices=[('personal', 'Personal'), ('Shop', 'Shop')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('acknowledgement_number', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('entry_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='update', max_length=10)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceEntry',
        ),
        migrations.DeleteModel(
            name='ServiceTempEntry',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
