# Generated by Django 5.1.4 on 2025-06-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_servicedepartment_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='actual_charge',
        ),
        migrations.AddField(
            model_name='service',
            name='other_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
