# Generated by Django 5.1.4 on 2025-10-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_servicetempentry_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='note',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='category',
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='api.account'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_cleared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='recurring_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='split_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='api.account'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='is_cleared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='recurring_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='split_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('mixed', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('mixed', 'Mixed')], max_length=10),
        ),
    ]
