# Generated by Django 5.1.4 on 2025-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_financetransaction_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('persoanl', 'Persoanl'), ('shop', 'Shop')], max_length=10, null=True),
        ),
    ]
