# Generated by Django 5.1.4 on 2025-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_amount_service_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='amount',
            new_name='agent_fee',
        ),
        migrations.AddField(
            model_name='service',
            name='required_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
