# Generated by Django 5.1.4 on 2025-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_service_actual_charge_service_other_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priority_level',
        ),
    ]
