# Generated by Django 5.1.4 on 2025-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_amount_service_agent_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_fees',
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
