# Generated by Django 5.1.4 on 2025-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.BooleanField(default=False, verbose_name='Is Personal'),
        ),
    ]
