# Generated by Django 5.1.4 on 2025-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_service_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
