# Generated by Django 5.1.4 on 2025-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='category_type',
            field=models.CharField(blank=True, choices=[('persoanl', 'Persoanl'), ('shop', 'Shop')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='category_type',
            field=models.CharField(blank=True, choices=[('persoanl', 'Persoanl'), ('shop', 'Shop')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('mixed', 'Mixed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('mixed', 'Mixed')], max_length=10, null=True),
        ),
    ]
