# Generated by Django 5.1.4 on 2025-06-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_service_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priority_level',
        ),
    ]
