# Generated by Django 5.1.4 on 2025-10-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_financetransaction_main_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransaction',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('update', 'Update')], default='update', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
