# Generated by Django 5.1.4 on 2025-06-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_service_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_department',
        ),
        migrations.DeleteModel(
            name='ServiceDepartment',
        ),
    ]
