# Generated by Django 5.1.4 on 2025-06-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_service_service_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('document_type', models.CharField(choices=[('Original', 'Original'), ('Xerox', 'Xerox')], max_length=10, verbose_name='Document Type')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='api.service', verbose_name='Service')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceRequirement',
        ),
    ]
