# Generated by Django 5.1.4 on 2025-03-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
