# Generated by Django 5.1.4 on 2025-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_servicetransaction_entry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTransactionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='global_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='global_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
