# Generated by Django 5.1.4 on 2025-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_globaltransactioncounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='is_split',
            field=models.BooleanField(default=False, verbose_name='Is Split Payment'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='is_split',
            field=models.BooleanField(default=False, verbose_name='Is Split Payment'),
        ),
    ]
