# Generated by Django 5.1.4 on 2025-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_financetransaction_is_split_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Transfer', 'Transfer'), ('Saving', 'Saving'), ('Debt', 'Debt')], max_length=20, null=True),
        ),
    ]
