# Generated by Django 5.1.4 on 2025-10-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_core_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='payment_method',
        ),
    ]
