# Generated by Django 5.1.4 on 2025-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_financetransaction_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
