# Generated by Django 5.1.4 on 2025-10-23 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_financetransaction_last_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetransaction',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='recurring_count',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='recurring_frequency',
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='due_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='due_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
