# Generated by Django 5.1.4 on 2025-10-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_servicetransaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financetransaction',
            old_name='recurring_count',
            new_name='tenure',
        ),
    ]
