# Generated by Django 5.1.4 on 2025-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_recurring_count_financetransaction_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Invest', 'Invest'), ('Saving', 'Saving'), ('Debt', 'Debt')], max_length=20, null=True),
        ),
    ]
