# Generated by Django 5.1.4 on 2025-03-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='agent_fee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paid_charge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_charge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pages_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=255)),
                ('requirement_type', models.CharField(choices=[('Document', 'Document'), ('Info', 'Information'), ('Verification', 'Verification')], default='Document', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN Card'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='api.user')),
            ],
        ),
    ]
