# Generated by Django 5.1.4 on 2025-10-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_category_core_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Investment', 'Investment')], max_length=20, null=True),
        ),
    ]
