# Generated by Django 5.1.4 on 2025-03-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_service_agent_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN Card'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Passport', 'Passport')], max_length=20, null=True),
        ),
    ]
