# Generated by Django 5.1.4 on 2025-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Loans', 'Loans'), ('Debts', 'Debts')], max_length=20, null=True),
        ),
    ]
