# Generated by Django 5.1.4 on 2025-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_userid_id_number_alter_userid_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
