# Generated by Django 5.1.4 on 2025-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userid_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Aadhaar', 'Aadhaar'), ('PAN', 'PAN Card'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Ration Card', 'Ration Card'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
