# Generated by Django 5.1.4 on 2025-03-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_mobile_number_alter_userid_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userid',
            old_name='custom_name',
            new_name='other_doc_name',
        ),
    ]
