# Generated by Django 5.1.4 on 2025-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_category_core_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Personal', 'Personal'), ('Investment', 'Investment'), ('Mutual Fund', 'Mutual Fund'), ('Digital Gold', 'Digital Gold'), ('Trading', 'Trading')], max_length=25, null=True),
        ),
    ]
