# Generated by Django 5.1.4 on 2025-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_custom_name_userid_other_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.JSONField(default=list),
        ),
    ]
