# Generated by Django 5.1.4 on 2025-10-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
