# Generated by Django 5.1.4 on 2025-10-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_financetransaction_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='reminder_date',
        ),
    ]
