# Generated by Django 5.1.4 on 2025-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='new', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('entry_time', models.CharField(blank=True, max_length=6, null=True)),
                ('enrollment_suffix', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UIDTempEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='new', max_length=10)),
                ('enrollment_suffix', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userid',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Aadhaar', 'Aadhaar'), ('Pancard', 'Pancard'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Ration Card', 'Ration Card'), ('BOCW', 'BOCW'), ('Aapaar ID', 'Aapaar ID'), ('ABHA ID', 'ABHA ID'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
