# Generated by Django 5.1.4 on 2025-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_uidentry_uidtempentry_alter_userid_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uidentry',
            name='uid_type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('ucl', 'UCL')], default='offline', max_length=15),
        ),
        migrations.AddField(
            model_name='uidtempentry',
            name='uid_type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('ucl', 'UCL')], default='offline', max_length=15),
        ),
    ]
