# Generated by Django 5.1.4 on 2025-10-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_financetransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], max_length=10, verbose_name='Category'),
        ),
    ]
