# Generated by Django 5.1.4 on 2025-03-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_uidentry_uid_type_uidtempentry_uid_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uidtempentry',
            name='enrollment_suffix',
        ),
    ]
