# Generated by Django 5.1.4 on 2025-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_account_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Savings', 'Savings'), ('Investments', 'Investments')], max_length=25),
        ),
    ]
