# Generated by Django 5.1.4 on 2025-03-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_uidtempentry_enrollment_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='uidentry',
            name='update_type',
            field=models.CharField(blank=True, choices=[('mobile_change', 'Mobile Number'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uidtempentry',
            name='update_type',
            field=models.CharField(blank=True, choices=[('mobile_change', 'Mobile Number Change'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name Change'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True),
        ),
    ]
