# Generated by Django 5.1.4 on 2025-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_account_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='issue_date',
        ),
    ]
