# Generated by Django 5.1.4 on 2025-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_uidentry_update_type_uidtempentry_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uidtempentry',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
