# Generated by Django 5.1.4 on 2025-10-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_account_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
