# Generated by Django 5.1.4 on 2025-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_uidtempentry_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uidtempentry',
            name='service_charge',
        ),
        migrations.AddField(
            model_name='uidentry',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
