# Generated by Django 5.1.4 on 2025-10-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_account_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_account_type',
            field=models.CharField(blank=True, choices=[('Fixed Deposit', 'Fixed Deposit'), ('SIP/Mutual Funds', 'SIP/Mutual Funds'), ('Gold', 'Gold'), ('Deposits', 'Deposits'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
