# Generated by Django 5.1.4 on 2025-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_uidtempentry_service_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidentry',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='uidtempentry',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
