# Generated by Django 5.1.4 on 2025-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_account_sub_account_type_alter_account_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_core',
            field=models.BooleanField(default=False, verbose_name='Is Core'),
        ),
    ]
