# Generated by Django 5.1.4 on 2025-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_uidentry_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidentry',
            name='entry_type',
            field=models.CharField(choices=[('new', 'New'), ('update', 'Update')], default='update', max_length=10),
        ),
        migrations.AlterField(
            model_name='uidentry',
            name='update_type',
            field=models.CharField(blank=True, choices=[('new_adhar', 'New Adhar'), ('mobile_change', 'Mobile Number'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uidtempentry',
            name='update_type',
            field=models.CharField(blank=True, choices=[('new_adhar', 'New Adhar'), ('mobile_change', 'Mobile Number Change'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name Change'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True),
        ),
    ]
