# Generated by Django 5.1.4 on 2025-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_category_is_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Savings', 'Savings'), ('Transfer', 'Transfer'), ('Investments', 'Investments'), ('Loans', 'Loans'), ('Debts', 'Debts')], max_length=20, null=True),
        ),
    ]
