# Generated by Django 5.1.4 on 2025-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_uidentry_entry_type_alter_uidentry_update_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uidentry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
    ]
