# Generated by Django 5.1.4 on 2025-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_category_core_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Family', 'Family'), ('Staff', 'Staff'), ('Owner', 'Owner'), ('Friend', 'Friend'), ('Agent', 'Agent'), ('Client', 'Client')], default='Customer', max_length=10, null=True),
        ),
    ]
