# Generated by Django 5.1.4 on 2025-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_uidentry_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name="Account Holder's Name")),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account Number')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=10)),
                ('bank_service_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Pigme', 'Pigme'), ('Fixed Deposit', 'Fixed Deposit')], default='Current', max_length=25)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Business', 'Business')], default='Business', max_length=10, verbose_name='Category')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'unique_together': {('account_holder_name', 'bank_service_name')},
            },
        ),
    ]
