# Generated by Django 5.1.4 on 2025-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='account_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='api_account_account_32cec2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_holder_name'], name='api_account_account_b5a926_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('account_holder_name', 'bank_service_name'), name='unique_account_holder_bank'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_method',
        ),
    ]
