# Generated by Django 5.1.4 on 2025-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_financetransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='intrest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
