# Generated by Django 5.1.4 on 2025-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_account_unique_together_account_account_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Account Holder's Name"),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Pigme', 'Pigme'), ('Fixed Deposit', 'Fixed Deposit')], default='Current', max_length=25, null=True),
        ),
    ]
