# Generated by Django 5.1.4 on 2025-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_financetransaction_intrest_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financetransaction',
            old_name='intrest_amount',
            new_name='interest_amount',
        ),
    ]
