# Generated by Django 5.1.4 on 2025-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_account_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Pigme', 'Pigme'), ('Fixed Deposit', 'Fixed Deposit')], max_length=25, null=True),
        ),
    ]
