# Generated by Django 5.1.4 on 2025-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_intrest_amount_financetransaction_interest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='debt_type',
            field=models.CharField(blank=True, choices=[('Borrow', 'Borrow'), ('Lend', 'Lend')], max_length=10, null=True),
        ),
    ]
