# Generated by Django 5.1.4 on 2025-10-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_financetransaction_debt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
