# Generated by Django 5.1.4 on 2025-05-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_account_account_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_holder_bank',
        ),
    ]
