# Generated by Django 5.1.4 on 2025-05-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_account_unique_account_holder_bank'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('account_holder_name', 'bank_service_name'), name='unique_account_holder_bank'),
        ),
    ]
