# Generated by Django 5.1.4 on 2025-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_account_unique_account_holder_bank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_holder_bank',
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Business', 'Business')], max_length=10, verbose_name='Category'),
        ),
    ]
