# Generated by Django 5.1.4 on 2025-10-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_shop_staff_shopattendance_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='close_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='effective_cost_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_foreclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='loan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='loan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='total_emi_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
