# Generated by Django 5.1.4 on 2025-10-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_financetransaction_close_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='disbursed_amount',
        ),
    ]
