# Generated by Django 5.1.4 on 2025-10-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_financetransaction_disbursed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='interest_paid',
        ),
    ]
