# Generated by Django 5.1.4 on 2025-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Pigme', 'Pigme'), ('Mutual Fund', 'Mutual Fund'), ('Digital Gold', 'Digital Gold'), ('Trading', 'Trading')], max_length=25, null=True),
        ),
    ]
