# Generated by Django 5.1.4 on 2025-05-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='uidentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.uidentry'),
        ),
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uidentry',
            name='update_type',
            field=models.CharField(blank=True, choices=[('new_adhar', 'New Adhar'), ('mobile_change', 'Mobile Number Change'), ('biometric_change', 'Biometric Change'), ('name_change', 'Name Change'), ('address_change', 'Address Change'), ('dob_change', 'Date of Birth Change')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='acknowledgment_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Money', 'Money'), ('Debt', 'Debt'), ('Invest', 'Invest'), ('Saving', 'Saving')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userservice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
    ]
