# Generated by Django 5.1.4 on 2025-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_financetransaction_interest_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='interest_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
