# Generated by Django 5.1.4 on 2025-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_financetransaction_interest_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
