# Generated by Django 5.1.4 on 2025-11-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_financetransaction_is_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=50, unique=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('first_emi_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='Next EMI due date', null=True)),
                ('total_emis_paid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_emi_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('tenure', models.PositiveIntegerField(blank=True, help_text='Tenure in months', null=True)),
                ('interest_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10, null=True)),
                ('interest_type', models.CharField(blank=True, choices=[('rate', 'Rate (%)'), ('amount', 'Amount (₹)')], default='rate', max_length=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('processing_fees', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('effective_cost_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overdue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_foreclosed', models.BooleanField(default=False)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('foreclosed', 'Foreclosed'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account')),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
    ]
