# Generated by Django 5.1.4 on 2025-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_emi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
