# Generated by Django 5.1.4 on 2025-11-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_recurringpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
