# Generated by Django 5.1.4 on 2025-11-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_recurringpayment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='type',
            field=models.CharField(choices=[('personal', 'Persoanl'), ('shop', 'Shop')], default='shop', max_length=20),
        ),
    ]
