# Generated by Django 5.1.4 on 2025-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_recurringpayment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='close_reason',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='closed_date',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='effective_cost_percent',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='interest_frequency',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='is_foreclosed',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='is_loan',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='loan_start_date',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='penalty_amount',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='principal_amount',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='total_emi_paid',
        ),
        migrations.AlterField(
            model_name='category',
            name='core_category',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Savings', 'Savings'), ('Transfer', 'Transfer'), ('Investments', 'Investments'), ('Debts', 'Debts')], max_length=20, null=True),
        ),
    ]
