# Generated by Django 5.1.4 on 2025-11-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_financetransaction_close_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='due_range_end',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='due_range_start',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='recurring_frequency',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='status',
        ),
    ]
