# Generated by Django 5.1.4 on 2025-11-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_financetransaction_due_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='due_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='due_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
